jobs:
  build_test:
    name: Build and Test on Java ${{ matrix.java-version }} and ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Install Java dependencies
      run: curl -s https://codecov.io/bash > $HOME/codecov-bash.sh && chmod +x $HOME/codecov-bash.sh
    - continue-on-error: true
      env:
        MVN_ARGS: -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      name: Execute Java unit tests
      run: mvn verify -fae -DskipITs $MVN_ARGS
    - continue-on-error: true
      env:
        CC_TOK: ${{ secrets.CODECOV_TOKEN }}
      if: github.ref == 'refs/heads/master'
      name: Publish Java code coverage
      run: $HOME/codecov-bash.sh -s modules/coverage-reports/target/site/jacoco-aggregate
        -t $CC_TOK
    strategy:
      matrix:
        java-version:
        - '8'
        os:
        - ubuntu-latest
name: Build and Test
on:
  repository_dispatch:
    types: trigger-ga___build-test.yml
