jobs:
  integration_test:
    name: Build and Run Integration Tests on Java ${{ matrix.java-version }} and ${{
      matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      env:
        ASSISTANT_APIKEY: ${{ secrets.WA_APIKEY }}
        ASSISTANT_ASSISTANT_ID: ${{ secrets.WA_ASSISTANT_ID }}
        ASSISTANT_URL: https://api.us-south.assistant.watson.cloud.ibm.com
        ASSISTANT_WORKSPACE_ID: ${{ secrets.WA_WORKSPACE_ID }}
        DISCOVERY_APIKEY: ${{ secrets.D1_APIKEY }}
        DISCOVERY_COLLECTION_ID: ${{ secrets.D1_COLLECTION_ID }}
        DISCOVERY_ENVIRONMENT_ID: ${{ secrets.D1_ENVIRONMENT_ID }}
        DISCOVERY_URL: https://api.us-south.discovery.watson.cloud.ibm.com
        DISCOVERY_V2_APIKEY: ${{ secrets.D2_APIKEY }}
        DISCOVERY_V2_COLLECTION_ID: ${{ secrets.D2_COLLECTION_ID }}
        DISCOVERY_V2_PROJECT_ID: ${{ secrets.D2_PROJECT_ID }}
        DISCOVERY_V2_URL: https://api.us-south.discovery.watson.cloud.ibm.com
        LANGUAGE_TRANSLATOR_APIKEY: ${{ secrets.LT_APIKEY }}
        LANGUAGE_TRANSLATOR_URL: https://api.us-south.language-translator.watson.cloud.ibm.com
        MVN_ARGS: -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        NATURAL_LANGUAGE_UNDERSTANDING_APIKEY: ${{ secrets.NLU_APIKEY }}
        NATURAL_LANGUAGE_UNDERSTANDING_URL: https://api.us-south.natural-language-understanding.watson.cloud.ibm.com
        SPEECH_TO_TEXT_ACOUSTIC_CUSTOM_ID: ${{ secrets.STT_APIKEY_ACOUSTIC_CUSTOM_ID
          }}
        SPEECH_TO_TEXT_APIKEY: ${{ secrets.STT_APIKEY }}
        SPEECH_TO_TEXT_CUSTOM_ID: ${{ secrets.STT_APIKEY_CUSTOM_ID }}
        SPEECH_TO_TEXT_URL: https://api.us-south.speech-to-text.watson.cloud.ibm.com
        TEXT_TO_SPEECH_APIKEY: ${{ secrets.TTS_APIKEY }}
        TEXT_TO_SPEECH_URL: https://api.us-south.text-to-speech.watson.cloud.ibm.com
      name: Execute Java integration tests
      run: 'mvn test -Dtest=v1/AssistantServiceIT -DfailIfNoTests=false -pl assistant,common
        $MVN_ARGS

        mvn test -Dtest=v2/AssistantServiceIT -DfailIfNoTests=false -pl assistant,common
        $MVN_ARGS

        mvn test -Dtest=v1/DiscoveryServiceIT -DfailIfNoTests=false -pl discovery,common
        $MVN_ARGS

        mvn test -Dtest=v2/DiscoveryIT -DfailIfNoTests=false -pl discovery,common
        $MVN_ARGS

        mvn test -Dtest=LanguageTranslatorIT -DfailIfNoTests=false -pl language-translator,common
        $MVN_ARGS

        mvn test -Dtest=NaturalLanguageUnderstandingIT -DfailIfNoTests=false -pl natural-language-understanding,common
        $MVN_ARGS

        mvn test -Dtest=SpeechToTextIT -DfailIfNoTests=false -pl speech-to-text,common
        $MVN_ARGS

        mvn test -Dtest=TextToSpeechIT -DfailIfNoTests=false -pl text-to-speech,common
        $MVN_ARGS

        mvn test -Dtest=CustomizationsIT -DfailIfNoTests=false -pl text-to-speech,common
        $MVN_ARGS

        '
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      if: false
      name: Notify slack on success
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: watson-e2e-tests
        color: good
        status: SUCCESS
    - continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      if: false
      name: Notify slack on failure
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: watson-e2e-tests
        color: danger
        status: FAILED
    strategy:
      matrix:
        java-version:
        - '8'
        os:
        - ubuntu-latest
name: Run Integration Tests
on:
  repository_dispatch:
    types: trigger-ga___integration-test.yml
